import React, { useState } from 'react';
import { ChevronDown, ChevronUp, Database, ShieldCheck, AlertCircle, Info, ExternalLink } from 'lucide-react';
import { EvidenceRecord } from '../../api/types';

interface EvidencePanelProps {
  evidence?: EvidenceRecord[];
  summary?: any;
  className?: string;
}

export const EvidencePanel: React.FC<EvidencePanelProps> = ({ evidence = [], summary, className = '' }) => {
  const [isOpen, setIsOpen] = useState(false);

  if (!evidence || evidence.length === 0) {
    return null;
  }

  const getStatusBadge = (status: string) => {
    switch (status.toUpperCase()) {
      case 'AVAILABLE':
        return <span className="px-2 py-0.5 text-[10px] font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 rounded">AVAILABLE</span>;
      case 'UNAVAILABLE':
        return <span className="px-2 py-0.5 text-[10px] font-semibold bg-rose-500/20 text-rose-300 border border-rose-500/30 rounded">UNAVAILABLE</span>;
      case 'STALE':
        return <span className="px-2 py-0.5 text-[10px] font-semibold bg-amber-500/20 text-amber-300 border border-amber-500/30 rounded">STALE</span>;
      default:
        return <span className="px-2 py-0.5 text-[10px] font-semibold bg-slate-500/20 text-slate-300 border border-slate-500/30 rounded">{status}</span>;
    }
  };

  const getFreshnessBadge = (freshness?: any) => {
    if (!freshness || !freshness.freshness_status) return null;
    const st = freshness.freshness_status.toUpperCase();
    if (st === 'FRESH') {
      return <span className="text-[10px] text-cyan-400 font-medium">• FRESH ({freshness.age_minutes ?? 0}m ago)</span>;
    } else if (st === 'RECENT') {
      return <span className="text-[10px] text-blue-400 font-medium">• RECENT ({freshness.age_minutes ?? 0}m ago)</span>;
    } else if (st === 'STALE') {
      return <span className="text-[10px] text-amber-400 font-medium">• STALE ({freshness.age_minutes ?? 0}m ago)</span>;
    }
    return <span className="text-[10px] text-slate-400 font-medium">• {st}</span>;
  };

  return (
    <div className={`rounded-xl border border-cyan-500/20 bg-ocean-900/60 overflow-hidden text-sm ${className}`}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-4 py-3 flex items-center justify-between bg-ocean-850/80 hover:bg-ocean-800 transition-colors text-left"
      >
        <div className="flex items-center gap-2.5">
          <Database className="w-4 h-4 text-cyan-400" />
          <span className="font-semibold text-slate-200">Scientific Evidence & Data Provenance</span>
          <span className="px-2 py-0.5 text-[11px] font-mono bg-cyan-950/60 text-cyan-300 rounded border border-cyan-500/30">
            {evidence.length} Sources
          </span>
          {summary?.completeness_score !== undefined && (
            <span className="text-xs text-slate-400">
              Score: <strong className="text-emerald-400">{summary.completeness_score}%</strong>
            </span>
          )}
        </div>
        {isOpen ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
      </button>

      {isOpen && (
        <div className="p-4 space-y-3 bg-ocean-950/80 border-t border-cyan-500/10 text-xs">
          <div className="text-slate-400 flex items-center gap-1.5 text-[11px] mb-2">
            <ShieldCheck className="w-3.5 h-3.5 text-cyan-400" />
            <span>All source attribution and authority classifications are generated by deterministic code.</span>
          </div>

          <div className="grid gap-2.5">
            {evidence.map((record, idx) => (
              <div
                key={idx}
                className="p-3 rounded-lg bg-ocean-900/90 border border-slate-800 flex flex-col gap-1.5"
              >
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <div className="font-semibold text-slate-200 flex items-center gap-2">
                      <span>{record.provider}</span>
                      <span className="text-slate-500 font-normal">/</span>
                      <span className="text-cyan-300 font-mono text-[11px]">{record.dataset}</span>
                    </div>
                    <div className="flex items-center gap-2 mt-0.5">
                      <span className="text-[10px] uppercase font-mono text-slate-400">{record.authority_class}</span>
                      <span className="text-slate-600">•</span>
                      <span className="text-[10px] uppercase font-mono text-slate-400">{record.data_class}</span>
                      {getFreshnessBadge(record.freshness)}
                    </div>
                  </div>
                  <div>{getStatusBadge(record.status)}</div>
                </div>

                {record.limitations && record.limitations.length > 0 && (
                  <div className="mt-1 p-2 rounded bg-amber-950/30 border border-amber-500/20 text-amber-300/90 text-[11px]">
                    <div className="font-medium text-amber-400 flex items-center gap-1 mb-0.5">
                      <Info className="w-3 h-3" /> Data Limitation:
                    </div>
                    <ul className="list-disc list-inside space-y-0.5">
                      {record.limitations.map((lim, lIdx) => (
                        <li key={lIdx}>{lim}</li>
                      ))}
                    </ul>
                  </div>
                )}

                <div className="flex items-center justify-between text-[10px] text-slate-500 pt-1 border-t border-slate-800/60">
                  <span>License: {record.license_type || 'Open Data'}</span>
                  <span>Retrieved: {record.retrieved_at ? new Date(record.retrieved_at).toLocaleTimeString() : 'N/A'}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
