name: geolocator_linux
description: No-op stub for geolocator_linux. This project targets Android only.
version: 0.2.6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator_platform_interface: ^4.0.0
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: geolocator
    platforms:
      linux:
        dartPluginClass: GeolocatorLinux
